config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root "properties#index"
    resources :properties, only: [:index, :new, :create, :show]
    devise_for :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/archetype.rb
class Archetype < ApplicationRecord
  def to_s
    name
  end
end

app/models/comfort.rb
class Comfort < ApplicationRecord
  validates :kitchen, :air_conditioning, :washing_machine, :dryer,
             :cabo_tv, :pet, :smoke, :accessibility, :elevator, :concierge, :pool, :service_area,
             :gym, :electric_iron, :notebook_space, :private_entrance, presence: false
end

app/models/property.rb
class Property < ApplicationRecord
  validates :title, :accommodates, :bathrooms, :number_of_rooms, :price, :description, presence: true
  belongs_to :archetype
  belongs_to :rule, required: false
  belongs_to :comfort, required: false
  accepts_nested_attributes_for :rule, allow_destroy: true
  accepts_nested_attributes_for :comfort, allow_destroy: true
end

app/models/rule.rb
class Rule < ApplicationRecord
  validates :description, presence: false
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
  before_action :set_locale

  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options = {})
    {locale: I18n.locale}
  end
end

app/controllers/properties_controller.rb
  class PropertiesController < ApplicationController

  def index
  end

  def new
    @property = Property.new
    @property.build_rule
    @property.build_comfort
  end

  def create
    @property = Property.new(property_params)

    if @property.valid? 
      @property.save
      flash[:notice] = I18n.t('.controllers.property.create.flash.notice')
      redirect_to @property 
    else
        render :new
    end
  end

  def show
    @property = Property.find(params[:id])
  end

  private

  def property_params
    params.require(:property).permit(:title, :accommodates,
                                     :bathrooms, :number_of_rooms,:furnished,
                                     :single_room, :share_room, :price, :description,
                                     :archetype_id,
                                     rule_attributes: [:id, :description, :created_at, :updated_at, :_destroy],
                                     comfort_attributes: [ :id, :kitchen, :tv, :air_conditioning, :washing_machine,
                                                           :dryer, :garage, :cabo_tv, :pet, :smoke, :accessibility,
                                                           :elevator, :intercom, :concierge, :pool, :service_area,
                                                           :gym, :electric_iron, :notebook_space, :private_entrance,
                                                            :_destroy
                                                          ]
                                     )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
  def title
    "Busco República"
  end
end

app/views/layouts/_flash_message.html.erb
<% flash.each do |message_type, message| %>
      <div class="container">
        <div class="row">
          <div class="card-content">
              <p><%= "#{message}" %></p>
          </div>
        </div>
      </div>
<% end %>

app/views/layouts/_header.html.erb
<header>

  <nav class="nav-bar">
    <div class="nav-wrapper">

      <a href="<%= root_path %>" class="brand-logo">
       <svg>
         <use xlink:href="<%= asset_path('page') %>#logo" />
       </svg>
      </a>

      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>

      <ul class="right hide-on-med-and-down" id="main-menu-nav">
        <li>
          <%= link_to I18n.t('.menu.register_fraternity'), new_property_path, class: 'btn red accent-2 btn-ad', method: :get %>
        </li>
        <li>
          <%= link_to I18n.t('.menu.signup'),  new_user_registration_path, method: :get %>
        </li>
        <li>
          <%= link_to I18n.t('.menu.signin'),  new_user_session_path, method: :get %>
        </li>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <li>
          <%= link_to I18n.t('.menu.register_fraternity'), new_property_path, class: 'btn red accent-2 btn-ad', method: :get %>
        </li>
        <li>
          <%= link_to I18n.t('.menu.signup'),  new_user_registration_path, method: :get %>
        </li>
        <li>
          <%= link_to I18n.t('.menu.signin'),  new_user_session_path, method: :get %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <%= title %>
    </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/header' %>

    <%= render 'layouts/flash_message' %>

    <main class="container">

      <%= yield %>
    </main>
  </body>
</html>

app/views/properties/_form.html.erb
<% if @property.errors.any? %>
  <div id="error_explanation">
    <h2>
       <%= "#{I18n.t('.form.message.invalid')} #{pluralize(@property.errors.count, I18n.t('.word.errors'))} #{I18n.t('.form.message.invalid_continue')}" %>
    </h2>
    <ul>
       <% @property.errors.full_messages.each do |message| %>
         <li><%= message %></li>
         <% end %>
    </ul>
   </div>
    <% end %>

<div class="row">
  <div class="col s12">
    <h2 class="properties_new_h2"><%= "#{t('.hi')}, Rodolfo! #{ t('.title_preparation_ad')}" %></h2>

  <%= simple_form_for(@property, html: { novalidate: true }) do |f| %>


    <div class="col s6">
        <h3>O espaço</h3>
        <hr>
    </div>

    <div class="input-field col s12">
      <%= f.input :title, required: true %>
    </div>


    <div class="input-field col s12">
      <%= f.input :description, as: :text, input_html: { class: "materialize-textarea", "data-length": 250} %>
    </div>

    <div class="input-field col s3">
      <%= f.association :archetype, collection: Archetype.all.map { |key| [I18n.t(".activerecord.attributes.archetype.#{key.name}"), key.id ] }, default: 1  %>
    </div>
    <div class="input-field col s3">
      <%= f.input :accommodates, input_html: { min: 1, max: 40 } %>
    </div>
    <div class="input-field col s3">
      <%= f.input :bathrooms, input_html: {  min: 1, max: 10 } %>
    </div>
    <div class="input-field col s3">
      <%= f.input :number_of_rooms, input_html: { min: 1, max: 20 } %>
    </div>
    <div class="input-field col s4">
      <%= f.input :furnished, as: :boolean, checked_value: true, unchecked_value: false %>
    </div>
    <div class="input-field col s4">
      <%= f.input :single_room, as: :boolean, checked_value: true, unchecked_value: false %>
    </div>

    <div class="input-field col s4">
      <%= f.input :share_room, as: :boolean %>
    </div>


    <div class="input-field col s2">
      <%= f.input :price %>
    </div>



    <div class="col s12">
        <h3>Regras da Casa</h3>
        <hr>
    </div>

    <%= f.simple_fields_for :rule do |r| %>
    <div class="input-field col s12">
      <%= r.input :description, as: :text, input_html: {class: "materialize-textarea", "data-length": 250} %>
    </div>

   <% end %>



    <div class="col s12">
        <h3>Comodidades</h3>
        <hr>
    </div>


    <%= f.simple_fields_for :comfort do |c| %>



      <div class="input-field col s3">
        <%= c.input :kitchen, as: :boolean, checked_value: true, unchecked_value: false %>
      </div>

      <div class="input-field col s3">
        <%= c.input :tv, as: :boolean, checked_value: true, unchecked_value: false %>
      </div>

      <div class="input-field col s3">
        <%= c.input :air_conditioning, as: :boolean, checked_value: true, unchecked_value: false %>
      </div>

      <div class="input-field col s3">
        <%= c.input :washing_machine, as: :boolean, checked_value: true, unchecked_value: false %>
      </div>



      <div class="input-field col s3">
        <%= c.input :dryer, as: :boolean, checked_value: true, unchecked_value: false %>
      </div>

      <div class="input-field col s3">
        <%= c.input :garage, as: :boolean, checked_value: true, unchecked_value: false %>
      </div>

      <div class="input-field col s3">
        <%= c.input :pet, as: :boolean, checked_value: true, unchecked_value: false %>
      </div>

      <div class="input-field col s3">
        <%= c.input :smoke, as: :boolean, checked_value: true, unchecked_value: false %>
      </div>



      <div class="input-field col s3">
        <%= c.input :accessibility, as: :boolean, checked_value: true, unchecked_value: false %>
      </div>

      <div class="input-field col s3">
        <%= c.input :elevator, as: :boolean, checked_value: true, unchecked_value: false %>
      </div>

      <div class="input-field col s3">
        <%= c.input :intercom, as: :boolean, checked_value: true, unchecked_value: false %>
      </div>

      <div class="input-field col s3">
        <%= c.input :concierge, as: :boolean, checked_value: true, unchecked_value: false %>
      </div>


      <div class="input-field col s3">
        <%= c.input :pool, as: :boolean, checked_value: true, unchecked_value: false %>
      </div>

      <div class="input-field col s3">
        <%= c.input :service_area, as: :boolean, checked_value: true, unchecked_value: false %>
      </div>

      <div class="input-field col s3">
        <%= c.input :gym, as: :boolean, checked_value: true, unchecked_value: false %>
      </div>

      <div class="input-field col s3">
        <%= c.input :cabo_tv, as: :boolean, checked_value: true, unchecked_value: false %>
      </div>



      <div class="input-field col s4">
        <%= c.input :notebook_space, as: :boolean, checked_value: true, unchecked_value: false %>
      </div>


      <div class="input-field col s4">
        <%= c.input :electric_iron, as: :boolean, checked_value: true, unchecked_value: false %>
      </div>

      <div class="input-field col s4">
        <%= c.input :private_entrance, as: :boolean, checked_value: true, unchecked_value: false %>
      </div>


    <% end %>


    <div class="input-field col s12">
      <%= f.button :button , name: 'action' %>
    </div>
<% end %>

  </div>
</div>

app/views/properties/index.html.erb
<h3><%= t ".no_property_registered" %></h3>

<p>
    <%= t ".text_no_property_registered" %>
</p>

<%= link_to t(".new_property"), new_property_path, class: "btn btn-small red accent-2", method: :get %>

app/views/properties/new.html.erb
<%= render 'form' %>

app/views/properties/show.html.erb
<div class="container">

   <h4>Imóvel</h4>
   <hr>

    <div class="col s12">
     <%= @property.title %>
    </div>

    <div class="row">
        <div class="col s6">
            <h5>Tipo de Imóvel</h5>
            <b><%= @property.archetype.name %></b>
        </div>
        <div class="col s6">
            <h5>Número de Acomodações</h5>
            <b><%= @property.accommodates %></b>
        </div>
    </div>
    <div class="row">
        <div class="col s6">
            <h5>Número de Banheiros</h5>
            <b><%= @property.bathrooms %></b>
        </div>
        <div class="col s6">
            <h5>Número de Quartos</h5>
            <b><%= @property.number_of_rooms %></b>
        </div>
    </div>
    <div class="row">
        <div class="col s6">
            <h5>Imobiliada</h5>
            <b><%= @property.furnished %></b>
        </div>
        <div class="col s6">
            <h5>Quarto Individual</h5>
            <b><%= @property.single_room %></b>
        </div>
    </div>
    <div class="row">
        <div class="col s6">
            <h5>Quarto Compartilhado</h5>
            <b><%= @property.share_room %></b>
        </div>
        <div class="col s6">
            <h5>Preço</h5>
            <b><%= @property.price %></b>
        </div>
    </div>

    <div class="row">
        <div class="col s12">
            <h5>Descrição</h5>
            <b><%= @property.description %></b>
        </div>
    </div>

    <h4>Regras da Casa</h4>
    <hr>
    <div class="col s12">
        <%= @property.rule.description %>
    </div>

</div>